Improve url detection
inthepocket/npm-license-scraper pull request #9
Opened 2021-12-10 12:41 UTC by GertjanReynaert

Make sure we always use an `https` url, instead of sometimes using `git+https` urls

2021-12-10 12:52 UTC, thibmaek requested changes

2021-12-10 12:52 UTC, thibmaek commented on src/packageUtils.ts
> +
```suggestion
  const [url] = [pkg.homepage, pkg.repository?.url, pkg.repository?.baseUrl, pkg.repo]
    .filter(Boolean)
    .filter(url => url.startsWith('https'));

```

2021-12-10 12:54 UTC, GertjanReynaert commented on src/packageUtils.ts
> +
🤦‍♂️

2021-12-13 08:52 UTC, thibmaek approved these changes

2021-12-13 08:52 UTC, merged